### ISSUE TITLE
你好请问下，冻结模型的问题

### ISSUE THREAD

**Issue by djh123** [RRanddom/tf_doc_localisation#10]
outputNodeNames = ["heats_map_regression/pred_keypoints/BiasAdd"]
input_checkpoint = "data/train_dir/model.ckpt-16212"
graph_def_file = "frozen_modeladdnode.pb"
input_name = "input"

with tf.Session(graph=tf.Graph()) as sess:
    inputImg = tf.placeholder(dtype=tf.float32, shape=(1, 800, 600, 3), name=input_name)
    saver = tf.train.import_meta_graph(input_checkpoint + '.meta', input_map={'IteratorGetNext:0':  inputImg}, clear_devices=True)
    saver.restore(sess, input_checkpoint)
    graph = tf.get_default_graph() # 获得默认的图
    graph_def = graph.as_graph_def()
    # tf.import_graph_def(graph_def, input_map={"IteratorGetNext:0": inputImg})
    # print(tf.get_default_graph().as_graph_def() == graph_def)
    # outputNodes = outputNodeNames.split(",")
    output_graph_def = tf.graph_util.convert_variables_to_constants(sess, graph_def, outputNodeNames)

    # Finally we serialize and dump the output graph to the filesystem
    with tf.gfile.GFile(graph_def_file, "wb") as f:
        f.write(output_graph_def.SerializeToString())

    input_arrays = [input_name]
    # converter = tf.lite.TFLiteConverter.from_frozen_graph(
    #         graph_def_file, input_arrays, outputNodeNames)
    # tflite_model = converter.convert()
    # open("255X340_frozen_model.tflite", "wb").write(tflite_model)

    converter = tf.lite.TocoConverter.from_frozen_graph(
    graph_def_file, input_arrays, outputNodeNames)
    tflite_model = converter.convert()
    open("frozen_model33.tflite", "wb").write(tflite_model)

**Comment by djh123** [comment]
使用转出来的tflite的模型不能用，结果不正确。而使用你的pb 转出来的tflite的模型确实可以用，结果正确。不知道有什么差异，请问你是怎么将cpkt转成pb再转成tflite的。是不是我中间漏了什么过程。

**Comment by phybrain** [comment]
@RRanddom 你是怎样转换pb 和tflite的，我的结果差异很大

**Comment by tunmx** [comment]
@djh123 你好，请问你解决这个问题了吗

**Comment by djh123** [comment]
解决了，is_training的问题

**Comment by luqiang6q** [comment]
> 解决了，is_training的问题

您好，麻烦问下is_training具体怎么修改啊
