### ISSUE TITLE
Hardcoded float32_t X[25][19] 

### ISSUE THREAD

**Issue by vkocheryzhkin** [RRanddom/tf_doc_localisation#16]
Can someone explain how did you get magic numbers
https://github.com/RRanddom/tf_doc_localisation/blob/master/Demo/Demo/TFHelper.mm#L46

Thank you

**Comment by vkocheryzhkin** [comment]
looks like equally distributed knots )

**Comment by JaosonMa** [comment]
did you know how did the magic numbers comes?
